region          = "ap-south-1"
vpc_name        = "java-with-nginx-vpc"
vpc_cidr        = "10.0.0.0/16"
ami             = "ami-00305d2fa3c93abfc"
key_name        = "id_rsa"
my-windows-keys = "id_rsa"
instance_type   = "t2.micro"